### ISSUE TITLE
Error when dumping reachable search space

### ISSUE THREAD

**Issue by jsego** [jendrikseipp/scorpion#14] opened 2024-05-09 13:54 UTC
The framework returns an error when dumping the reachable search space of gripper test.

Command:
`./fast-downward.py misc/tests/benchmarks/gripper/domain.pddl misc/tests/benchmarks/gripper/prob01.pddl --search "dump_reachable_search_space()"`

Error:
`Critical error in file [...]/scorpion/src/search/utils/../plugins/options.h, line 90: 
Attempt to retrieve nonexisting object of name verbosity (type: utils::Verbosity)`

**Comment by jendrikseipp** [comment] 2024-05-10 08:12
Thanks for reporting this! The issue is fixed now.

**Closed by jendrikseipp** 2024-05-10 08:12 UTC
